version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  mongo:
    image: "mongo"
    hostname: mongo
    container_name: mongo
    ports:
      - "27017:27017"
  front:
    image: jeee187/front-converter
    hostname: front-converter
    container_name: front-converter
    ports:
      - "8080:8080"
    depends_on:
      - "rabbitmq"
      - "mongo"
    links:
      - "rabbitmq:rabbitmq"
      - "mongo:mongo"
  worker:
      image: jeee187/worker-converter
      hostname: worker-converter
      container_name: worker-converter
      ports:
        - "9000:9000"
      depends_on:
        - "rabbitmq"
        - "mongo"
      links:
        - "rabbitmq:rabbitmq"
        - "mongo:mongo"
        - "front:front-converter"
      volumes:
        - vol-worker:/tmp/jpg
  reverse-proxy:
      build: ./reverse-proxy/
      hostname: reverse-proxy
      container_name: reverse-proxy
      ports: 
        - "8181:8181"
      depends_on:
        - "front"
      links:
        - "front:front-converter"
volumes:
    vol-worker:
